name: Build and upload result
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Build and Publish
        run: ./gradlew clean build
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: build/libs/*